### ISSUE TITLE
Question on Barlow Twins

### ISSUE THREAD

**Issue by EmreTaha** [ADevillers/EquiMod#1]
Hi, Thanks for this interesting work. I have a question regarding to barlow twins. Did you use barlow twins  on the equivariance branch as well or did you keep the ntxent loss?
Also is equivariant predictor linear or non-linear?

Thanks,

**Comment by ADevillers** [comment]
Hello! Thank you for your questions.

Regarding your first question, for the equivariance objective, we utilized the NT-Xent loss on all the baseline models, including Barlow Twins.

As for your second question, the equivariant predictor architecture we employed in our experiments consisted of a fully connected layer followed by a batch normalization layer. You can refer to Figure 2.b in our research paper for more details on the different architecture experiments conducted for the equivariant predictor.

I hope this clarifies your queries. If you have any further questions, please feel free to ask.
